# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Nuitka Packaging

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest
    env:
      PACKAGENAME: Generator_windows_x64
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyside6==6.9.1
    - uses: Nuitka/Nuitka-Action@main
      with:
        nuitka-version: main
        mode: standalone
        script-name: qt/app.py
        enable-plugins: pyside6
        windows-icon-from-ico: assets/icon.ico
        nofollow-import-to: http,email
    - name: Build
      run: |
        mv build/app.dist Generator
        rm Generator/qt6network.dll
        rm Generator/qt6pdf.dll
        rm Generator/libcrypto-3.dll
        rm Generator/PySide6/QtNetwork.pyd
        7z a -t7z -r "$($Env:PACKAGENAME + '.7z')" "Generator"
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.PACKAGENAME }}
        path: Generator
  macos:
    runs-on: macos-latest
    env:
      PACKAGENAME: Generator_macos
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyside6==6.9.1
      - uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          mode: app-dist
          script-name: qt/app.py
          enable-plugins: pyside6
          nofollow-import-to: http,email
      - name: Build
        run: |
          mv build/app.app Generator.app
          zip -r "${{ env.PACKAGENAME }}.zip" "Generator.app"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PACKAGENAME }}
          path: Generator.app